# Generated by Django 4.2.4 on 2024-04-08 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerModel',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('on', models.BooleanField()),
                ('manual', models.BooleanField()),
            ],
            options={
                'db_table': 'controllerTable',
            },
        ),
        migrations.CreateModel(
            name='GreenhouseModel',
            fields=[
                ('uid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('beginDate', models.DateTimeField()),
                ('photo', models.ImageField(null=True, upload_to='image/greenhouse_photo', verbose_name='Greenhouse Avatar')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greenhouse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'greenhouseTable',
                'ordering': ['owner', '-beginDate'],
            },
        ),
        migrations.CreateModel(
            name='RealSensorModel',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nameKey', models.CharField(max_length=64)),
                ('electricity', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realSensor', to='greenhouse_data.greenhousemodel')),
            ],
            options={
                'db_table': 'realSensorTable',
            },
        ),
        migrations.CreateModel(
            name='EvalvePropertyModel',
            fields=[
                ('controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evalveProperty', serialize=False, to='greenhouse_data.controllermodel')),
                ('cutHumidity', models.FloatField()),
                ('duration', models.DurationField()),
                ('startTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'evalvePropertyTable',
            },
        ),
        migrations.CreateModel(
            name='ShadePropertyModel',
            fields=[
                ('controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shadeProperty', serialize=False, to='greenhouse_data.controllermodel')),
                ('openTemp', models.FloatField()),
                ('closeTemp', models.FloatField()),
            ],
            options={
                'db_table': 'shadePropertyTable',
            },
        ),
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('currentValue', models.FloatField()),
                ('parentItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='greenhouse_data.realsensormodel')),
            ],
            options={
                'db_table': 'sensorTable',
            },
        ),
        migrations.CreateModel(
            name='RealControllerModel',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nameKey', models.CharField(max_length=64)),
                ('electricity', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realController', to='greenhouse_data.greenhousemodel')),
            ],
            options={
                'db_table': 'realControllerTable',
            },
        ),
        migrations.CreateModel(
            name='EvalveScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutHumidity', models.FloatField()),
                ('duration', models.DurationField()),
                ('startTime', models.DateTimeField()),
                ('evalveProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalveSchedule', to='greenhouse_data.controllermodel')),
            ],
            options={
                'db_table': 'evalveScheduleTable',
            },
        ),
        migrations.AddField(
            model_name='controllermodel',
            name='parentItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='greenhouse_data.realcontrollermodel'),
        ),
    ]
