# Generated by Django 5.0.4 on 2024-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greenhouse_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllermodel",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="controllermodel",
            name="lng",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="realsensormodel",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="realsensormodel",
            name="lng",
            field=models.FloatField(null=True),
        ),
    ]
