# Generated by Django 4.2.4 on 2024-04-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllermodel',
            name='greenhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='greenhouse_data.greenhousemodel'),
        ),
        migrations.AlterField(
            model_name='sensorvaluehistorymodel',
            name='isCurrent',
            field=models.BooleanField(default=True),
        ),
    ]
