# Generated by Django 5.0.4 on 2024-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_data', '0002_alter_controllermodel_greenhouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllermodel',
            name='name',
            field=models.CharField(default='not_implemented', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realsensormodel',
            name='name',
            field=models.CharField(default='not_implemented', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realsensormodel',
            name='realSensorKey',
            field=models.CharField(default='not_implemented', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensormodel',
            name='name',
            field=models.CharField(default='not', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realsensormodel',
            name='realSensorID',
            field=models.CharField(max_length=32),
        ),
    ]
