# Generated by Django 4.2.4 on 2024-04-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_data', '0003_fanpropertymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalveschedulemodel',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='realcontrollermodel',
            name='greenhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realControllers', to='greenhouse_data.greenhousemodel'),
        ),
        migrations.AlterField(
            model_name='realsensormodel',
            name='greenhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realSensors', to='greenhouse_data.greenhousemodel'),
        ),
    ]
