# Generated by Django 4.2.4 on 2024-04-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_data', '0004_remove_evalveschedulemodel_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllermodel',
            name='parentItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='greenhouse_data.realcontrollermodel'),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='parentItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='greenhouse_data.realsensormodel'),
        ),
    ]
