# Generated by Django 4.2.4 on 2024-04-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_data', '0005_alter_controllermodel_parentitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalveschedulemodel',
            name='evalveProperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalveSchedules', to='greenhouse_data.evalvepropertymodel'),
        ),
    ]
