# Generated by Django 4.2.4 on 2024-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_data', '0006_alter_evalveschedulemodel_evalveproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhousemodel',
            name='beginDate',
            field=models.DateField(),
        ),
    ]
