# Generated by Django 4.2.4 on 2024-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_data', '0007_alter_greenhousemodel_begindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalveschedulemodel',
            name='startTime',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
