# Generated by Django 5.0.4 on 2024-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformationmodel",
            name="name",
            field=models.CharField(default="Daniel", max_length=32),
            preserve_default=False,
        ),
    ]
