# Generated by Django 5.0.4 on 2024-05-10 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_userinformationmodel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinformationmodel",
            old_name="Email",
            new_name="email",
        ),
    ]
